# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks: 
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '(\.Rd|algorithms/.*)$'
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.2
    hooks: 
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: style-files
        args: [--cache-root=styler, --style_pkg=styler, --style_fun=tidyverse_style]    
    -   id: lintr
        args: [--warn_only]
        verbose: false
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        exclude: '^(best_confs|test_results|train_results)\.rds$'
        
ci:
    autoupdate_schedule: monthly
